name: Deploy Travel Carib on EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/Travel-Carib
            pm2 stop all
            git pull origin master
            npm install
            npx prisma generate
            pm2 start index.ts --name=travel-carib
